/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tarificador;
/**
 *
 * @author Diego
 */
public class CalculadoraTarifaCorreos extends javax.swing.JFrame {

    int m_com_box_producto;
    int m_com_box_pesos;
    int producto;
    int peso;
    float vd; // Valor declarado
    float av; // Aviso de recibo  
    float resultado;
    
    
    public CalculadoraTarifaCorreos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        but_group_cat = new javax.swing.ButtonGroup();
        but_group_mod = new javax.swing.ButtonGroup();
        label_categoria = new javax.swing.JLabel();
        rad_but_nacional = new javax.swing.JRadioButton();
        rad_but_internacional = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        rad_but_ordinaria = new javax.swing.JRadioButton();
        rad_but_urgente = new javax.swing.JRadioButton();
        label_producto = new javax.swing.JLabel();
        com_box_producto = new javax.swing.JComboBox<>();
        label_pesos = new javax.swing.JLabel();
        com_box_pesos = new javax.swing.JComboBox<>();
        ch_box_valorDeclarado = new javax.swing.JCheckBox();
        ch_box_avisoRecibo = new javax.swing.JCheckBox();
        btn_calcular = new javax.swing.JButton();
        txtF_resultado = new javax.swing.JTextField();
        txtF_valorDeclarado = new javax.swing.JTextField();
        label_info = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N

        label_categoria.setText("Seleccione la categoría");

        but_group_cat.add(rad_but_nacional);
        rad_but_nacional.setText("Nacional");

        but_group_cat.add(rad_but_internacional);
        rad_but_internacional.setText("Internacional");
        rad_but_internacional.setEnabled(false);

        jLabel1.setText("Seleccione el modelo de envío");

        but_group_mod.add(rad_but_ordinaria);
        rad_but_ordinaria.setText("Ordinaria");
        rad_but_ordinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_but_ordinariaActionPerformed(evt);
            }
        });

        but_group_mod.add(rad_but_urgente);
        rad_but_urgente.setText("Urgente");
        rad_but_urgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_but_urgenteActionPerformed(evt);
            }
        });

        label_producto.setText("Seleccione el producto");

        com_box_producto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cartas y tarjetas postales", "Cartas certificadas" }));
        com_box_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_box_productoActionPerformed(evt);
            }
        });

        label_pesos.setText("Pesos");

        com_box_pesos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hasta 20g normalizadas", "Más de 20g(incluída) hasta 50g", "Más de 50g hasta 100g", "Más de 100 hasta 500g", "Más de 500g hasta 1.000g", "Más de 1.000 hasta 2.000g" }));
        com_box_pesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_box_pesosActionPerformed(evt);
            }
        });

        ch_box_valorDeclarado.setText("Valor declarado");

        ch_box_avisoRecibo.setText("Aviso de recibo");

        btn_calcular.setText("Calcular");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        txtF_resultado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        txtF_valorDeclarado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(label_categoria)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_producto)
                                    .addComponent(ch_box_avisoRecibo)
                                    .addComponent(label_pesos))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(com_box_pesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(com_box_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(ch_box_valorDeclarado)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtF_valorDeclarado)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rad_but_ordinaria, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rad_but_nacional, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rad_but_internacional, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rad_but_urgente, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(btn_calcular))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtF_resultado, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(label_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(label_categoria)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rad_but_nacional)
                    .addComponent(rad_but_internacional))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rad_but_ordinaria)
                    .addComponent(rad_but_urgente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(com_box_producto))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_pesos)
                    .addComponent(com_box_pesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ch_box_valorDeclarado)
                    .addComponent(ch_box_avisoRecibo)
                    .addComponent(txtF_valorDeclarado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_calcular)
                .addGap(18, 18, 18)
                .addComponent(txtF_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_info, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void com_box_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_box_productoActionPerformed
        m_com_box_producto = com_box_producto.getSelectedIndex();
        label_info.setText(Integer.toString(m_com_box_producto));
        switch(m_com_box_producto) { 
            case 0 -> producto = m_com_box_producto; // Cartas y tarjetas postales    
            case 1 -> {
                producto = m_com_box_producto; // Cartas certificadas
                av = (float) (1.60 + 0.34); // Se sumaría el aviso de recibo al resultado final                
            }
        }
    }//GEN-LAST:event_com_box_productoActionPerformed

    private void com_box_pesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_box_pesosActionPerformed
        m_com_box_pesos = com_box_pesos.getSelectedIndex();
        switch(m_com_box_pesos) { // Pesos
            case 0 -> peso = m_com_box_pesos;
            case 1 -> peso = m_com_box_pesos;
            case 2 -> peso = m_com_box_pesos;
            case 3 -> peso = m_com_box_pesos;
            case 4 -> peso = m_com_box_pesos;
            case 5 -> peso = m_com_box_pesos;            
        }
    }//GEN-LAST:event_com_box_pesosActionPerformed

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        calcular();
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void rad_but_ordinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_but_ordinariaActionPerformed
        ch_box_avisoRecibo.setEnabled(false);
        ch_box_valorDeclarado.setEnabled(false);
        txtF_valorDeclarado.setEnabled(false);
    }//GEN-LAST:event_rad_but_ordinariaActionPerformed

    private void rad_but_urgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_but_urgenteActionPerformed
        ch_box_avisoRecibo.setEnabled(true);
        ch_box_valorDeclarado.setEnabled(true);
        txtF_valorDeclarado.setEnabled(true);
    }//GEN-LAST:event_rad_but_urgenteActionPerformed
    
    
    
    private void preciosPesosOrdinaria(){
        if(producto == 0) { // Cartas y tarjetas postales
            label_info.setText("");
            if(peso == 0) resultado = (float) 0.70;
            if(peso == 1) resultado = (float) 0.80;
            if(peso == 2) resultado = (float) 1.25;
            if(peso == 3) resultado = (float) 2.50;
            if(peso == 4) resultado = (float) 5.15;
            if(peso == 5) resultado = (float) 5.60;
        }

        if(producto == 1){ // Cartas certificaddas  
            label_info.setText("");
            if(peso == 0) resultado = (float) 4.15;
            if(peso == 1) resultado = (float) 4.25;
            if(peso == 2) resultado = (float) 4.70;
            if(peso == 3) resultado = (float) 5.95;
            if(peso == 4) resultado = (float) 8.60;
            if(peso == 5) resultado = (float) 9.05;
        }
    }
    
    
    private void preciosPesosUrgentes(){
        // En el resultado ponemos el valor del producto y la suma del IVA, por si en un futuro cambia algún precio.
        if(producto == 0) { // Cartas y tarjetas postales URGENTES
            label_info.setText("");
            if(peso == 0) resultado = (float) (3.39 + 0.71); 
            if(peso == 1) resultado = (float) (3.49 + 0.73); 
            if(peso == 2) resultado = (float) (3.92 + 0.82); 
            if(peso == 3) resultado = (float) (5.27 + 1.11); 
            if(peso == 4) resultado = 0; 
            if(peso == 5) resultado = 0;
        }
        
        if(producto == 1) { // Cartas certificaddas URGENTES
            label_info.setText("");                   
            if(peso == 0) resultado = (float) (6.84 + 1.44);
            if(peso == 1) resultado = (float) (6.94 + 1.46);
            if(peso == 2) resultado = (float) (7.37 + 1.55);
            if(peso == 3) resultado = (float) (8.72 + 1.83);
            if(peso == 4) resultado = (float) (11.57 + 2.43);
            if(peso == 5) resultado = (float) (12.05 + 2.53);
        }
    }
    
    
    
    
    private void calcular(){
        if(rad_but_nacional.isSelected()) {
            
            label_info.setText("");
            
            if(rad_but_ordinaria.isSelected()) { // Ordinaria ( Sin IVA )
                
                preciosPesosOrdinaria();                              
                txtF_resultado.setText(String.valueOf("Resultado = "+resultado+"€"));
                
            } else if(rad_but_urgente.isSelected()) { // Urgente ( con IVA )
                
                preciosPesosUrgentes();
                
                if(resultado > 0) {

                    label_info.setText("");
                    
                    if(ch_box_avisoRecibo.isSelected()) {
                        
                        // Añadimos el valor total del Aviso de recibo si se selecciona la opción
                        resultado = resultado + av;     
                        txtF_resultado.setText(String.valueOf("Resultado = "+resultado+"€"));
                    }
                    
                    if(ch_box_valorDeclarado.isSelected()) {
                        
                        // Controlamos si el usuario introduce decimales, por si acaso
                        vd = Float.parseFloat(txtF_valorDeclarado.getText());
                        
                        // El tope hoy en día está en 3.000€ pero lo controlo hasta 500
                        if(vd >= 1 && vd <= 50) resultado = (float) (resultado + 2.10); 
                        else if(vd >= 51 && vd <= 100) resultado = (float) (resultado + 4.20); 
                        else if(vd >= 101 && vd <= 150) resultado = (float) (resultado + 6.30);
                        else if(vd >= 151 && vd <= 200) resultado = (float) (resultado + 8.40);
                        else if(vd >= 201 && vd <= 250) resultado = (float) (resultado + 10.50);
                        else if(vd >= 251 && vd <= 300) resultado = (float) (resultado + 12.60);
                        else if(vd >= 301 && vd <= 350) resultado = (float) (resultado + 14.70);
                        else if(vd >= 351 && vd <= 400) resultado = (float) (resultado + 16.80);
                        else if(vd >= 401 && vd <= 450) resultado = (float) (resultado + 18.90);
                        else if(vd >= 451 && vd <= 500) resultado = (float) (resultado + 20.00);
                        else if(vd >= 501) resultado = (float) (resultado + 22.10);
                        
                        txtF_resultado.setText(String.valueOf("Resultado = "+resultado+"€"));
                    } else {
                        txtF_resultado.setText(String.valueOf("Resultado = "+resultado+"€"));
                    }                                        
                } else {
                    // Si hubiera un botón de enviar lo cancelaríamos
                    txtF_resultado.setText(String.valueOf("Resultado = "+resultado+"€"));
                    label_info.setText("No se pueden enviar más de 500g");                   
                }
                
            } else {
                label_info.setText("Ups, se le ha pasado escoger el modelo de envío");
            }
        } else {
            label_info.setText("Para continuar, seleccione la categoría nacional");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraTarifaCorreos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraTarifaCorreos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular;
    private javax.swing.ButtonGroup but_group_cat;
    private javax.swing.ButtonGroup but_group_mod;
    private javax.swing.JCheckBox ch_box_avisoRecibo;
    private javax.swing.JCheckBox ch_box_valorDeclarado;
    private javax.swing.JComboBox<String> com_box_pesos;
    private javax.swing.JComboBox<String> com_box_producto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_categoria;
    private javax.swing.JLabel label_info;
    private javax.swing.JLabel label_pesos;
    private javax.swing.JLabel label_producto;
    private javax.swing.JRadioButton rad_but_internacional;
    private javax.swing.JRadioButton rad_but_nacional;
    private javax.swing.JRadioButton rad_but_ordinaria;
    private javax.swing.JRadioButton rad_but_urgente;
    private javax.swing.JTextField txtF_resultado;
    private javax.swing.JTextField txtF_valorDeclarado;
    // End of variables declaration//GEN-END:variables
}